[package]
name = "chal8"
version = "0.1.0"
authors = ["Matthew Wynn <matthew@matthewwynn.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"hex" = "*"
